### PR TITLE
Avoid sentry swallowing log messages

### PR DESCRIPTION
**Pull request by theMarix**
This resolves an issue we observe in our set-up where log messages no longer end up in central log aggregation.

Sadly I have not really found a good way to automatically test this. If you have one I'll be more than happy to amend the PR. For now I have only locally reproduced the issue and manually verified that both logging and Sentry work as expected if applied.

### CODE REVIEW

**Comment by StephanErb** [comment]
Could you elaborate why this fixes the issue? Both the code before and after look healthy to me (maybe except the missing flask extra requirement).

**Comment by theMarix** [comment]
I should probably have included the commit message of the last commit into the PR description:

> For a pre-defined set of loggers, like the Gunicorn loggers, Sentry
> will register itself and disable propagation. However, this means any
> handlers registered on the root level, like custom formatting stream
> loggers or forwarding to central log aggregation will no longer get to
> see these messages.

**Comment by sebastianneubauer** [comment]
awesome, way beyond my knowledge of logging and sentry... 👏

**Comment by theMarix** [comment]
Coverage decreased because I removed "covered" code.

**Pull request merged**
